root = "."
testdata_dir = "testdata"
tmp_dir = "bin"

[build]
  # Command to build your app
  cmd = "go build -o ./bin/main ./cmd/main.go"
  bin = "./bin/main"             # Output binary path
  full_bin = ""                  # Optional: full build path override
  args_bin = []                  # Optional: arguments passed to binary after build

  delay = 1000                   # Delay after file change (ms)
  kill_delay = "0s"              # Wait before killing old binary

  # Directories/files to include/exclude
  exclude_dir = ["assets", "bin", "vendor", "testdata"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false      # Rebuild if content hasn’t changed?
  include_dir = []
  include_file = []
  include_ext = ["go", "tpl", "tmpl", "html"]

  follow_symlink = false
  log = "build-errors.log"       # Write build errors here

  # Optional shell commands
  pre_cmd = []
  post_cmd = []

  rerun = false
  rerun_delay = 500              # Time between re-run checks (ms)

  send_interrupt = false         # Send SIGINT before killing
  stop_on_error = false          # Stop running binary on build error

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  silent = false
  time = false                   # Log timestamps

[misc]
  clean_on_exit = false          # Remove tmp files on exit

[proxy]
  enabled = false
  app_port = 0
  proxy_port = 0

[screen]
  clear_on_rebuild = false
  keep_scroll = true

